### ISSUE TITLE
TCA: categories are missing

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/fluidcontent_core#220] opened 2016-03-26 14:44 UTC
Hi,

the categories tab for Plugins is missing if fcc is installed. For other elements too. I think tie override TCA is wrong. Can someone confirm?

**Comment by NamelessCoder** [comment] 2016-04-11 00:57
Hi @mithri - confirmed; but the cause is not so much incorrect as *intentionally minimal* TCA. You can add the field anywhere you like (with displayCond or selectively by `tt_content` type).

Will close this one since `fluidcontent_core` faces an operation which will remove all the TCA decisions completely; making it "just" Flux integration for `fluid_styled_content`.

**Closed by NamelessCoder** 2016-04-11 00:57 UTC
