### ISSUE TITLE
Exception with 7.5-dev new FromEngine

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/fluidcontent_core#195] opened 2015-09-10 07:28 UTC
Open a CE or FCE in Backend.

Backtrace
```

Uncaught TYPO3 Exception
#1: PHP Warning: Illegal offset type in isset or empty in /var/www/typo3conf/ext/fluidcontent_core/Classes/Service/ConfigurationService.php line 109 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/var/www/typo3_src/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 107.

21 TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "Illegal offset type in isset or empty", "/var/www/typo3conf/ext/fluidcontent_core/Classes/Service/ConfigurationService.php", 109, array)


/var/www/typo3conf/ext/fluidcontent_core/Classes/Service/ConfigurationService.php:

00107:   */
00108:  public function getVariantExtensionKeysForContentType($contentType) {

00109:   if (TRUE === isset($this->variants[$contentType])) {

00110:    return $this->variants[$contentType];
00111:   }


20 FluidTYPO3\FluidcontentCore\Service\ConfigurationService::getVariantExtensionKeysForContentType(array)


/var/www/typo3conf/ext/fluidcontent_core/Classes/UserFunction/ProviderField.php:

00064:   */
00065:  public function createVariantsField(array $parameters) {

00066:   $extensionKeys = $this->configurationService->getVariantExtensionKeysForContentType($parameters['row']['CType']);

00067:   $defaults = $this->configurationService->getDefaults();
00068:   $preSelected = $parameters['row']['content_variant'];


19 FluidTYPO3\FluidcontentCore\UserFunction\ProviderField::createVariantsField(array, TYPO3\CMS\Backend\Form\Element\UserElement)

18 call_user_func_array(array, array)


/var/www/typo3_src/typo3/sysext/core/Classes/Utility/GeneralUtility.php:

04184:      }
04185:      // Call method:

04186:      $content = call_user_func_array(array(&$classObj, $parts[1]), array(&$params, &$ref));

04187:     } else {
04188:      $errorMsg = 'No method name \'' . $parts[1] . '\' in class ' . $parts[0];


17 TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction("FluidTYPO3\FluidcontentCore\UserFunction\ProviderField->createVariantsField", array, TYPO3\CMS\Backend\Form\Element\UserElement)


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Element/UserElement.php:

00040:    $parameterArray,
00041:    $this

00042:   );

00043:   return $resultArray;
00044:  }


16 TYPO3\CMS\Backend\Form\Element\UserElement::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/SingleFieldContainer.php:

00179:     $options['renderType'] = $parameterArray['fieldConf']['config']['type'];
00180:    }

00181:    $resultArray = $this->nodeFactory->create($options)->render();

00182:    $html = $resultArray['html'];
00183: 


15 TYPO3\CMS\Backend\Form\Container\SingleFieldContainer::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php:

00208: 
00209:     $options['renderType'] = 'singleFieldContainer';

00210:     $singleFieldContentArray = $this->nodeFactory->create($options)->render();

00211: 
00212:     if (!empty($singleFieldContentArray['html'])) {


14 TYPO3\CMS\Backend\Form\Container\PaletteAndSingleContainer::createPaletteContentArray("general")


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php:

00115:    $fieldName = $fieldConfiguration['fieldName'];
00116:    if ($fieldName === '--palette--') {

00117:     $paletteElementArray = $this->createPaletteContentArray($fieldConfiguration['paletteName']);

00118:     if (!empty($paletteElementArray)) {
00119:      $mainStructureCounter ++;


13 TYPO3\CMS\Backend\Form\Container\PaletteAndSingleContainer::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/TabsContainer.php:

00087:    }
00088:    $options['renderType'] = 'paletteAndSingleContainer';

00089:    $childArray = $this->nodeFactory->create($options)->render();

00090: 
00091:    $tabsContent[] = array(


12 TYPO3\CMS\Backend\Form\Container\TabsContainer::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/FullRecordContainer.php:

00081:   }
00082: 

00083:   return $this->nodeFactory->create($data)->render();

00084:  }
00085: 


11 TYPO3\CMS\Backend\Form\Container\FullRecordContainer::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Form/Container/OuterWrapContainer.php:

00050:    $options['renderType'] = 'listOfFieldsContainer';
00051:   }

00052:   $result = $this->nodeFactory->create($options)->render();

00053: 
00054:   $childHtml = $result['html'];


10 TYPO3\CMS\Backend\Form\Container\OuterWrapContainer::render()


/var/www/typo3_src/typo3/sysext/backend/Classes/Controller/EditDocumentController.php:

01030: 
01031:         $formData['renderType'] = 'outerWrapContainer';

01032:         $formResult = $nodeFactory->create($formData)->render();

01033: 
01034:         $html = $formResult['html'];

```

**Comment by NamelessCoder** [comment] 2015-09-10 14:19
Hmm, this makes no sense. The parameter that is being read is `$parameters['row']['CType']` and it wouldn't be an array unless some code either changed it to an array (which would make no sense) or some TCA changed the `CType` field to a multivalued field (which also makes no sense).

I have to close this one as cannot be reproduced. If you do find out *why* the `CType` of the row has become an array - if for example this is a new practice toggled on by some parameter in TYPO3 that I didn't activate - then please create a new issue that specifies that reason. However, I'm not exactly sure it should be our responsibility to support multivalued `CType` fields... ;)

**Comment by xf-** [comment] 2015-09-10 21:49
Issue, select is now an array.
This is logical, a select could be a multi select. Allows new possibilitys :)

**Comment by NamelessCoder** [comment] 2015-09-13 16:12
> Issue, select is now an array.

Yep, that would be the only possible explanation.

> This is logical, a select could be a multi select. Allows new possibilitys :)

It is not logical - at all, imho. I still consider this a bug and I'm still unable to reproduce on master of TYPO3. Reasons for closing:

* I'm unable to reproduce this; I've tried to closely make the same setup you describe but regardless what I try to edit and change in any language, it still works. Whatever the reason is, the problem doesn't exist in a "raw" TYPO3 master with just flux, fluidpages etc. installed.
* The input for the function in question comes from the DB. If it is transformed before being returned, that's a HUGE breaking change. I can only assume it is a bug; a temporary problem. I just can't imagine that it's intentional because that would be... catastrophic. Not just for us.
* Yes, the select *can* be multivalued. But it isn't, not in this configuration. And the type cannot (in native TCA) be changed dynamically from/to multiselect. And the type of the input field would only affect the **posted** data - it wouldn't break as you say when you "open" an element and certainly not in the frontend.

There really is no good reason why this value would be an array at this point in the code. It has to be a temporary problem or you have to report it to the core's bug tracker instead. If this is intentional which I highly doubt, it is so tremendously destructive in both BE and FE that it would be insane not to have it as a feature that can at least be switched OFF by default. Because transforming data as it gets pulled from the DB... I'm getting nightmares tonight.

Please don't reopen - report to the core instead. `CType` just simply must not be multivalued, ever.

**Closed by NamelessCoder** 2015-09-13 16:12 UTC
